Repository hlxsites/vg-volvotrucks-us, pull requests merged in 2024-09, with the labels that each got.

#727 532 - add magazines metadata to search
  helix-query.yaml
Labels: Magazine

#728 NHTSA Search Bar Displaying Incorrect Text #676
  blocks/vin-number/vin-number.js
Labels: bugfix

#731 Release 21
  .github/ci/generate-news-feed-config.js
  .github/ci/generate-news-feed.js
  .github/workflows/generate-atom-news-feed.yaml
  blocks/vin-number/vin-number.js
  common/modal/modal.js
  constants.json
  package-lock.json
  package.json
  scripts/common.js
Labels: Ignore for release

#739 Remove all caps from article cards block #702
  blocks/v2-article-cards/v2-article-cards.css
Labels: enhancement

#743 Social block changes #540
  blocks/v2-social-block/v2-social-block.css
Labels: FR

#758 Release 22
  blocks/magazine-articles/magazine-articles.css
  blocks/magazine-articles/magazine-articles.js
  blocks/search/autosuggest.js
  blocks/search/search-api.js
  blocks/search/search.js
  blocks/v2-article-cards/v2-article-cards.css
  blocks/v2-social-block/v2-social-block.css
  blocks/v2-stories-carousel/v2-stories-carousel.css
  blocks/v2-stories-carousel/v2-stories-carousel.js
  blocks/vin-number/vin-number.js
  constants.json
  head.html
  package-lock.json
  package.json
  placeholder.json
  scripts/common.js
  scripts/delayed.js
  scripts/magazine-press.js
  scripts/scripts.js
  scripts/search-api.js
  scripts/validate-countries.js
  styles/styles.css
Labels: Ignore for release

#766 HotFix: image & author correctly checked
  blocks/magazine-articles/magazine-articles.js
Labels: bugfix
