Repository hlxsites/vg-volvotrucks-us, pull requests merged in 2024-10, with the labels that each got.

#767 Implement pagination module for v2-article-cards #602
  blocks/v2-article-cards/v2-article-cards.js
  common/pagination/pagination.css
  common/pagination/pagination.js
  icons/chevron-left.svg
  icons/chevron-right.svg
  placeholder.json
Labels: FR

#770 Adapt v2-video block for AEM videos
  blocks/v2-video/v2-video.css
  blocks/v2-video/v2-video.js
  templates/v2-magazine/v2-magazine.css
Labels: Injection

#771 Release 23
  blocks/v2-article-cards/v2-article-cards.js
  blocks/v2-video/v2-video.css
  blocks/v2-video/v2-video.js
  common/pagination/pagination.css
  common/pagination/pagination.js
  icons/chevron-left.svg
  icons/chevron-right.svg
  package-lock.json
  package.json
  placeholder.json
  templates/v2-magazine/v2-magazine.css
Labels: Ignore for release
