Repository hlxsites/vg-volvotrucks-us, pull requests merged in 2024-08, with the labels that each got.

#694 Apply redesign typography on magazine article #633
  blocks/v2-text/v2-text.css
  blocks/v2-text/v2-text.js
  styles/styles.css
  templates/v2-magazine/v2-magazine.css
Labels: FR

#687 Article cards 1 and 2 link variations #619
  blocks/v2-article-cards/v2-article-cards.css
  blocks/v2-article-cards/v2-article-cards.js
  placeholder.json
Labels: FR

#692 Magazine article cards dynamic feed #680
  blocks/v2-article-cards/v2-article-cards.css
  blocks/v2-article-cards/v2-article-cards.js
Labels: FR

#696 Preventing duplicate articles from appearing in dynamic article list #681
  blocks/v2-article-cards/v2-article-cards.css
  blocks/v2-article-cards/v2-article-cards.js
Labels: FR

#673 Alert for content editors on incorrect block usage #539
  common/snackbar/snackbar.css
  common/snackbar/snackbar.js
  constants.json
  icons/checkmark-circle.svg
  icons/remove.svg
  scripts/common.js
  scripts/delayed.js
  scripts/validate-elements.js
  styles/styles.css
Labels: NFR

#703 Stories Carousel design changes #545
  blocks/v2-stories-carousel/v2-stories-carousel.css
  blocks/v2-stories-carousel/v2-stories-carousel.js
Labels: FR

#719 Release 20
  blocks/v2-stories-carousel/v2-stories-carousel.css
  blocks/v2-stories-carousel/v2-stories-carousel.js
  common/snackbar/snackbar.css
  common/snackbar/snackbar.js
  constants.json
  icons/checkmark-circle.svg
  icons/remove.svg
  package-lock.json
  package.json
  scripts/common.js
  scripts/delayed.js
  scripts/validate-elements.js
  styles/styles.css
Labels: Ignore for release
